spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: rootuser1
  kafka:  
    bootstrap-servers: localhost:9092  
    producer:
     bootstrap-servers: localhost:9092  
     key-serializer: org.apache.kafka.common.serialization.StringSerializer
     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
   
    consumer: 
     bootstrap-servers: localhost:9092 
     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
     properties:
      spring:
       json:
        trusted:
         packages: com.jpmc.midascore.foundation.Transaction
       deserializer:
        value:
         delegate:
          class: org.apache.kafka.common.serialization.ByteArrayDeserializer
         default:
          type: false
general:
  kafka-topic: midas-transaction

